<?php
$title = 'Supprimer un lieu';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Êtes-vous sur de supprimer le lieu
    '<?php echo $this->escapeHtml($lieu->getNom()); ?>'?
</p>
<?php
$url = $this->url('lieu/delete', array(
    'id' => $this->id,
    ));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $lieu->getId(); ?>" />
        <input type="submit" name="del" value="Oui" />
        <input type="submit" name="del" value="Non" />
    </div>
</form>