<?php
$title = 'Détails d\'une conférence';
$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>
<p>
    <b>Nom de la conférence :</b> <?php echo $this->escapeHtml($conference->getNom()); ?>
</p>
<p>
    <b>Détails :</b> <?php echo $this->escapeHtml($conference->getDescriptif()); ?>
</p>
<?php if($conference->getDateDebut()) :?>
<p>
    <b>Date de début :</b> <?php echo $this->escapeHtml($conference->getDateDebut()->format('Y-m-d')); ?>
</p>
<?php endif; ?>
<?php if($conference->getLieu()) :?>
<p>
    <b>Lieu :</b> <?php echo $this->escapeHtml($conference->getLieu()->getNom());?>
</p>
<?php endif; ?>