<?php
$title = 'Modifier une conférence';
$this->headTitle($title);
//var_dump($lieux);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>
<?=$this->form()->openTag($form->setAttribute('class', 'form-horizontal')->setAttribute('novalidate', 'novalidate'))?>
<div class="form-group <?php if($form->get('nom')->getMessages()) echo "has-error"; ?>">
    <?=$this->formLabel($form->get('nom')->setLabelAttributes(array('class' => 'col-sm-2 control-label')))?>
    <div class="col-sm-10">
        <?=$this->formElement($form->get('nom')->setAttribute('class', 'form-control'))?>
    </div>
    <span class="help-block">
        <?=$this->formElementErrors($form->get('nom'))?>
    </span>
</div>
<div class="form-group <?php if($form->get('descriptif')->getMessages()) echo "has-error"; ?>">
    <?=$this->formLabel($form->get('descriptif')->setLabelAttributes(array('class' => 'col-sm-2 control-label')))?>
    <div class="col-sm-10">
        <?=$this->formElement($form->get('descriptif')->setAttribute('class', 'form-control'))?>
    </div>
    <span class="help-block">
        <?=$this->formElementErrors($form->get('descriptif'))?>
    </span>
</div>
<div class="form-group <?php if($form->get('date_debut')->getMessages()) echo "has-error"; ?>">
    <?=$this->formLabel($form->get('date_debut')->setLabelAttributes(array('class' => 'col-sm-2 control-label')))?>
    <div class="col-sm-10">
        <?=$this->formDateTime($form->get('date_debut')->setAttribute('class', 'form-control'))?>
    </div>
    <span class="help-block">
        <?=$this->formElementErrors($form->get('date_debut'))?>
    </span>
</div>
<div class="form-group <?php if($form->get('lieu_id')) ; ?>">
    <?=$this->formLabel($form->get('lieu_id')->setLabelAttributes(array('class' => 'col-sm-2 control-label')))?>
    <div class="col-sm-10">
        <?php //$form->get('lieu_id')->setValueOptions($lieux); ?>
        <?=$this->formSelect($form->get('lieu_id')->setAttribute('class', 'form-control')->setValueOptions($lieux))?>
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">Modifier</button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>